export const GET_ADMIN_EDIT_MOVIE = 'GET_ADMIN_EDIT_MOVIE';

export const GET_ADMIN_MOVIE_LIST = 'GET_ADMIN_MOVIE_LIST';

export const GET_ADMIN_USER_LIST = 'GET_ADMIN_USER_LIST';

export const POST_ADMIN_BOOKING_HISTORY = 'POST_ADMIN_BOOKING_HISTORY';

