export const GET_SEAT_BOOKING_LIST = 'GET_SEAT_BOOKING_LIST';

export const POST_SEAT_BOOKING = 'POST_SEAT_BOOKING';

export const FINISH_SEAT_BOOKING = 'FINISH_SEAT_BOOKING';

export const SEAT_SELECTION = 'SEAT_SELECTION'